services:
  vmlinuz:
    build:
      target: vmlinuz
      dockerfile: Containerfile
      context: .
      args:
        LINUX_VERSION: 6.13.5

    volumes:
      - ./out:/out:z

    command:
      - sh
      - -c
      - cp vmlinuz-* /out/

  initramfs:
    build:
      target: initramfs
      dockerfile: Containerfile
      context: .
      args:
        BUSYBOX_VERSION: 1.36.1
        JQ_VERSION: 1.7.1
        ORAS_VERSION: 1.2.2

    volumes:
      - ./out:/out:z

    command:
      - sh
      - -c
      - cp initramfs-* /out/

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data: null
